table Customer
	lineageTag: 7fe3bce8-9df4-48ae-9f06-3d19bef043ad

	measure TotalSAle = SUM(Sales[Sales Amount])
		lineageTag: 51eb409d-c66e-4700-a116-6790eee42052

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Name = USERPRINCIPALNAME()
		lineageTag: 0c45e4a8-e9ca-4dbf-a05c-fb64e1b52ead

	measure Measure = PATHCONTAINS()
		lineageTag: 4112d039-9e80-4538-b7ed-ff245cf726bd

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 2130009d-14f0-4b66-947d-5cf17b28e60f
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 9e52304b-682d-4248-8203-90e771f91482
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 417250bb-24ab-4b0e-ba0a-737141f6b674
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 9007f68d-43b3-4c4c-99cf-ff6aa071b67f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: 0d500470-a859-45e3-bf58-733e71989e32
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: 95f3369b-2e3c-4b02-b3ad-e8c1e8695ad4
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: bf7e2ded-bbbf-43e3-a196-5a3a75b8ec31
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Power BI Source\AdventureWorks Sales.xlsx"), null, true),
				    Customer_Table = Source{[Item="Customer",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Customer_Table,{{"CustomerKey", Int64.Type}, {"Customer ID", type text}, {"Customer", type text}, {"City", type text}, {"State-Province", type text}, {"Country-Region", type text}, {"Postal Code", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

