table Date
	lineageTag: f2997016-01cc-4755-9497-5c2545bc3229
	dataCategory: Time

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: a7e0ae25-f95f-4c7a-b605-21529bc32864
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: bba8dbf6-164a-4fd3-a370-439247a3af59
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: string
		lineageTag: 245a0515-16b2-4bb8-9f8f-1c148ae11714
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: b59100b4-d7c9-4bce-b74e-6e85f1227018
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 71d98f75-4811-4603-b44d-e2edf4f4d57f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Full Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4d1a763e-6e7a-4c08-97ee-3ee3770381d6
		summarizeBy: none
		sourceColumn: Full Date

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: int64
		formatString: 0
		lineageTag: b970f3b5-350b-4886-891c-0aac30fc9c6a
		summarizeBy: count
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Power BI Source\AdventureWorks Sales.xlsx"), null, true),
				    Date_Table = Source{[Item="Date",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Date_Table,{{"DateKey", Int64.Type}, {"Date", type date}, {"Fiscal Year", type text}, {"Fiscal Quarter", type text}, {"Month", type date}, {"Full Date", type datetime}, {"MonthKey", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Full Date] >= RangeStart and [Full Date] < RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

