table SalesOrder
	lineageTag: e911da96-8f44-48db-965c-d276dd8dbd65

	column Channel
		dataType: string
		lineageTag: 3026b91e-c5d8-499c-974d-f00c4a0b3fb6
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineKey
		dataType: int64
		formatString: 0
		lineageTag: efa666c2-bbae-4112-b600-74474765fcb3
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column 'Sales Order'
		dataType: string
		lineageTag: 1331f256-608a-4b90-a397-118431952d81
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

	column 'Sales Order Line'
		dataType: string
		lineageTag: c27aa451-c559-44db-a228-efb8cacc7c13
		summarizeBy: none
		sourceColumn: Sales Order Line

		annotation SummarizationSetBy = Automatic

	partition SalesOrder = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Power BI Source\AdventureWorks Sales.xlsx"), null, true),
				    SalesOrder_Table = Source{[Item="SalesOrder",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(SalesOrder_Table,{{"Channel", type text}, {"SalesOrderLineKey", Int64.Type}, {"Sales Order", type text}, {"Sales Order Line", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

